const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync('index.html','utf8'),script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(script);
const context={Intl,Date};vm.createContext(context);
vm.runInContext(script.slice(script.indexOf(' function timestamp('),script.indexOf(' let audioContext;')),context);
const printedAt=Date.UTC(2026,9,4,14),resetAt=printedAt+86400000;
const record={printedAt,warning:{label:'周额度',remaining:0,resetAt}};
const red=context.warningMarkup(1,record);
assert(red.includes('打印时距重置')&&red.includes('1天 0小时 0分'));
assert(!red.includes('data-reset-at')&&!red.includes('alert-countdown'));
assert(!script.includes('setInterval')&&!script.includes('refreshCountdowns'));
const cyan=context.resetMarkup({reset:{resetAt:printedAt,window:{label:'周额度',remaining:97,resetAt}}});
assert(cyan.includes('额度已重置')&&cyan.includes('97%')&&cyan.includes('aria-valuenow="97"'));
assert(cyan.includes('重置时间')&&cyan.includes('下次重置'));
assert(!html.includes('演示'));
const current={label:'周额度',remaining:64,minutes:10080,resetAt};
const manualYellow=context.makeSpecialReceipt('yellow',current,printedAt,'Y001');
const manualRed=context.makeSpecialReceipt('red',current,printedAt,'R002');
const manualCyan=context.makeSpecialReceipt('cyan',current,printedAt,'C003');
assert(manualYellow.warningOnly&&context.level(1,manualYellow.warning.remaining)==='yellow');
assert(manualRed.warningOnly&&context.level(1,manualRed.warning.remaining)==='red');
assert(manualCyan.resetOnly&&!manualCyan.warningOnly&&manualCyan.reset.window.remaining===100);
assert.equal(manualCyan.reset.window.resetAt,printedAt+10080*60000);
assert.equal(context.makeSpecialReceipt('invalid',current,printedAt,'X'),null);
assert.equal(context.level(1,10.1),'normal');assert.equal(context.level(1,10),'yellow');
assert.equal(current.remaining,64,'Manual printing does not change actual quota');
const showcase=context.makeShowcaseRecords(current,printedAt);
const order=Array.from(showcase).flatMap(record=>record.resetOnly?['cyan']:['normal',...record.warnings.map(w=>context.level(1,w.remaining))]);
assert.deepEqual(order,['normal','normal','normal','normal','yellow','normal','red','cyan']);
assert.equal(showcase[3].windows[0].remaining,9.8);assert.equal(showcase[4].windows[0].remaining,0);
assert(showcase.every(record=>record.showcase&&record.demo));
console.log('PASS: script syntax, static red reset snapshot, cyan observed quota and reset times, no demo labels.');
